org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=false

minecraft_version=26.1.2
loader_version=0.19.3
fabric_api_version=0.150.0+26.1.2
loom_version=1.16-SNAPSHOT

mod_id=portalmod
mod_name=PortalMod
mod_version=2.0.0-alpha.1
mod_license=All rights reserved
mod_group_id=net.portalmod
mod_authors=SerialSniper, PhantomEye, LarsMans
mod_description=Portal in Minecraft, reimagined.
